### ISSUE TITLE
Hex codes don't match documentation

### ISSUE THREAD

**Issue by pauldraper** [AjaniBilby/BNF-parser#15]
The documentation says that hex escapes work like `"\x6b"` but the actually behavior is `"x6b"`.

**Comment by AjaniBilby** [comment]
I clearly foolishly relied on Javascript's `parseInt` to work in the correct edianness....

**Comment by AjaniBilby** [comment]
Whoops, it was actually something else.
I'm already fixed it and added an automated check for it.
Publishing a patch now
