### ISSUE TITLE
Error with default BNF example

### ISSUE THREAD

**Issue by thekevinscott** [AjaniBilby/BNF-parser#18]
Hello,

Running through the [homepage example](https://bnf-parser.ajanibilby.com/), I use the following BNF:

```
program ::= %w* statement+ ;
block   ::= %("block" w+) ...name %(w* "{" w*) seq_stmt* %("}" w*) ;
```

And run:

```
npx bnf-compile ./syntax.bnf
```

And I get:

```
Found: ./syntax.bnf

 - Compiling syntax
   Encoding Parser
Parse Error: Unknown term name "w" (1:14) -> (1:16)
```

**Comment by AjaniBilby** [comment]
Ahh sorry, that example is abbreviated, for instance it doesn't include the definition for `seq_stmt` or `name` either - I'll think up a better example and update it.

But for now, here are some other sample bnfs from the automated [testing](https://github.com/AjaniBilby/BNF-parser/tree/main/test/bnf), and the actual bnf definition that defines the bnf syntax [here](https://github.com/AjaniBilby/BNF-parser/blob/main/bnf/bnf.bnf)

**Comment by AjaniBilby** [comment]
Documentation updates are now live
