### ISSUE TITLE
Example code is not working properly

### ISSUE THREAD

**Issue by lordofdestiny** [AjaniBilby/BNF-parser#3]

**Comment by AjaniBilby** [comment]
Sorry, I meant to release the new version as a beta, and I'm now hurriedly fixing the bugs now that's is public

**Comment by AjaniBilby** [comment]
They all work on my end now, and there are also automated tests to validate in the future

[![Test](https://github.com/AjaniBilby/BNF-parser/actions/workflows/test.yml/badge.svg)](https://github.com/AjaniBilby/BNF-parser/actions/workflows/test.yml)

That being said I'm having some issues with Github action environments at the moment, but when I run it locally all the tests pass
