### ISSUE TITLE
This library cannot even handle the simplest test cases:

### ISSUE THREAD

**Issue by tippfelher** [AjaniBilby/BNF-parser#7]
```
// OK
let result = BNF.parse(`program ::= "aa" | "a";`);
let tree = Compile(result);
let syntax = tree.parse("aa");
console.log("result", result, "syntax", syntax);
```

```
// Not OK
let result = BNF.parse(`program ::= "a" | "aa";`);
let tree = Compile(result);
let syntax = tree.parse("aa");
console.log("result", result, "syntax", syntax);
```

**Comment by AjaniBilby** [comment]
I'm adding this as a automated test case just in case for future builds, however NPM is down for me and I want to make sure the two syntaxes from the different BNFs should make identical output syntax trees

**Comment by tippfelher** [comment]
"bnf-parser": "^3.1.1",

I will try to make a better report. (already deleted everything after it failed xD)

**Comment by AjaniBilby** [comment]
I managed to replicate your error - I have no idea how I didn't run into this when I have an actual programming language running off this as the syntax parser 😅

**Comment by tippfelher** [comment]
All good. I needed a bnf parser yesterday and started to built one. Then I realized that, what I reported above, won't be handled by my parser and so I started to look out for existing solutions. (yours is the fist I checked)

**Comment by AjaniBilby** [comment]
I thought it was a bug just like you, but I realized it's actually expected behavior - the library assumes not parsing the whole string is a failure. So in your second case it would match the "a", then the program ends, but there is still a remaining character so it fails.

For both cases to be valid you would need to write it like this:
```bnf
case1 ::= ( "a" | "aa" )+
case2 ::= ( "aa" | "a" )+
```

**Comment by AjaniBilby** [comment]
> All good. I needed a bnf parser yesterday and started to built one. Then I realized that, what I reported above, won't be handled by my parser and so I started to look out for existing solutions. (yours is the first I checked)

Yeh, that's basically why I started mine as well, plus why I adapted BNF syntax to have the ommit character for easy clean up and stuff - the only thing I'm really unhappy with atm is the fact that sometimes it gives the wrong reference range for a syntax error.
> i.e. if you have a syntax error in a function, it complains it can't parse at the start of the function body, instead of at the statement in the function

**Comment by AjaniBilby** [comment]
@tippfelher, this might be a bit late, but I was thinking there are probably other people like you who expect a more non-deterministic select statement.
I was wondering do you think it would be worth adding a variant of `||` form `|`, where if you use `||` it will match all cases then return the best (consumes the most tokens) result, and `|` always just returns the first match. Thoughts?
